# -*- mode: ruby -*-
# vi: set ft=ruby :

# Kubernetes for Home Network provisioner
# Inspired by by Artur Scheiner - artur.scheiner@gmail.com

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_version = "202112.19.0"
  config.vm.provider :vmware_desktop do |v, override|
    v.ssh_info_public = true
    v.gui = true
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    v.vmx["ethernet0.connectiontype"] = "bridged"
  end

  config.vm.define "host-2-win-amd64-k8s-master-0" do |node|
    node.vm.hostname = "host-2-win-amd64-k8s-master-0"
    node.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "2048"
      v.vmx["ethernet0.addressType"] = "static"
      v.vmx["ethernet0.address"] = "00:0C:29:0F:F6:C3"
    end

    node.vm.provision "install-app", type: "shell", path: "./scripts/install-k8s.sh"
  end

end
