---
- name: VM config directory
  ansible.builtin.file:
    path: ~/.lima/{{ vm_name }}
    state: directory
    mode: "0755"

- name: VM config
  ansible.builtin.template:
    src: templates/lima.yaml.j2
    dest: ~/.lima/{{ vm_name }}/lima.yaml
    mode: "0644"
  vars:
    vm_cpu: "{{ virtual_machine.cpu }}"
    vm_memory: "{{ virtual_machine.memory }}"
    vm_disk: "{{ virtual_machine.disk }}"
  notify: vm reconfig

- name: Wait for handlers
  ansible.builtin.meta: flush_handlers

- name: Start VM
  ansible.builtin.command:
    cmd: limactl start {{ vm_name }} --tty=false
    creates: ~/.lima/{{ vm_name }}/*.pid
  register: vm_start
  changed_when: "{{ vm_start.rc != 0 }}"

- name: Copy SSH config
  ansible.builtin.copy:
    src: ~/.lima/{{ vm_name}}/ssh.config
    dest: "{{ vm_name }}-ssh.config"
