---
- name: Create a VM (async)
  community.general.lxd_container:
    name: "{{ vm.name }}"
    ignore_volatile_options: true
    state: started
    type: virtual-machine
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases/
      protocol: simplestreams
      alias: "22.04"
    config:
      limits.cpu: "{{ vm.config.cpu | default(vm_cpu) }}"
      limits.memory: "{{ vm.config.memory | default(vm_memory) }}"
    devices:
      eth0:
        type: nic
        network: lxdbr0
        ipv4.address: "{{ vm.config.ipv4_address | default('auto') }}"
      root:
        path: /
        pool: homenet-k8s
        size: "{{ vm.config.disk | default(vm_disk) }}"
        type: disk
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  async: 300
  delay: 5
  poll: 0
  register: virtual_machine_start_async
  loop: "{{ virtual_machines | dict2items(key_name='name', value_name='config') }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  become: true

- name: Wait for virtual machines
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: virtual_machine_wait
  until: virtual_machine_wait.finished
  delay: 10
  retries: 30
  loop: "{{ virtual_machine_start_async.results }}"
  become: true

- name: Enable SSH to VM
  block:
    - name: Copy SSH authorised public keys to VM
      ansible.builtin.command: lxc file push {{ ansible_user_dir }}/.ssh/authorized_keys {{ vm.name }}/root/.ssh/authorized_keys
      register: lxc_push
      changed_when: lxc_push.rc != 0
      loop: "{{ virtual_machines | dict2items(key_name='name', value_name='config') }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.name }}"
      become: true
