---
- name: Virtual machine config
  ansible.builtin.template:
    src: templates/lima.yaml.j2
    dest: "/tmp/{{ virtual_machine_name }}.yaml"
    mode: "0644"
  register: virtual_machine_config

- name: Restart the virtual machine
  ansible.builtin.shell:
    cmd: |-
      if [ "{{ virtual_machine_config.changed }}" == "true" ]; then
        limactl remove {{ virtual_machine_name }} --force
      fi
      limactl start {{ virtual_machine_config.dest }} --tty=false
    creates: ~/.lima/{{ virtual_machine_name }}/lima.yaml
