---
- name: Install Minikube
  tags: minikube_deps
  block:
    - name: Install Minikube and drivers
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - minikube
        - socket_vmnet
        - qemu
    - name: Install services for Homebrew
      community.general.homebrew_tap:
        name: homebrew/services
    - name: Start socket_vmnet service
      ansible.builtin.command:
        cmd: brew services restart socket_vmnet
        creates: /Library/LaunchDaemons/homebrew.mxcl.socket_vmnet.plist
      environment:
        HOMEBREW_NO_INSTALL_FROM_API: "1"
      become: true

- name: Launch Minikube
  tags: minikube
  block:
    - name: Destroy cluster if rebuilding
      when: rebuild_cluster
      ansible.builtin.command:
        cmd: minikube delete
        removes: ~/.minikube/machines/minikube/config.json
    - name: Create cluster
      ansible.builtin.command:
        cmd: minikube start --driver qemu --network socket_vmnet
        creates: ~/.minikube/machines/minikube/config.json
    - name: Enable addons
      ansible.builtin.command:
        cmd: minikube addons enable {{ item }}
      register: minikube_addons_enable
      changed_when: minikube_addons_enable.rc != 0
      loop:
        - ingress
