apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ginolatorilla/k8s-homenet.git
        revision: ansible-minikube
        directories:
          - path: kubernetes/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/ginolatorilla/k8s-homenet.git
        targetRevision: ansible-minikube
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'