fullnameOverride: postgresql

global:
  storageClass: openebs-hostpath

architecture: replication

primary:
  resources:
    requests:
      cpu: 15m
      memory: 100M
    limits:
      memory: 150M

readReplicas:
  resources:
    requests:
      cpu: 15m
      memory: 120M
    limits:
      memory: 180M
