fullnameOverride: postgresql

global:
  storageClass: openebs-hostpath
  postgresql:
    auth:
      existingSecret: postgresql

architecture: replication

primary:
  initdb:
    scripts:
      init.sh: |
        createdb -U postgres vault
        createuser -U postgres vault
        psql -U postgres -c "\c vault;
        GRANT ALL PRIVILEGES ON DATABASE VAULT to vault;
        CREATE TABLE vault_kv_store (
          parent_path TEXT COLLATE "C" NOT NULL,
          path        TEXT COLLATE "C",
          key         TEXT COLLATE "C",
          value       BYTEA,
          CONSTRAINT pkey PRIMARY KEY (path, key)
        );
        CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);"

  resources:
    requests:
      cpu: 15m
      memory: 100M
    limits:
      memory: 150M

readReplicas:
  resources:
    requests:
      cpu: 15m
      memory: 120M
    limits:
      memory: 180M
