---
- name: Personal Certificate Authority
  block:
    - name: Signing key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ ansible_user_id }}.pem"
      register: ownca_privatekey

    - name: Signing request
      community.crypto.openssl_csr:
        path: "/tmp/{{ ansible_user_id }}.csr"
        privatekey_path: "{{ ownca_privatekey.filename }}"
        common_name: "{{ ansible_user_id }}"
        create_subject_key_identifier: true
        use_common_name_for_san: false
        basic_constraints:
          - "CA:TRUE"
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr

    - name: Own CA
      community.crypto.x509_certificate:
        path: "/tmp/{{ ansible_user_id }}-ca.crt"
        privatekey_path: "{{ ownca_privatekey.filename }}"
        csr_path: "{{ ca_csr.filename }}"
        provider: selfsigned
      register: ca_crt

- name: Ingress SSL certificate
  block:
    - name: Signing key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ cluster_name }}.pem"
      register: certs_ingress_self_signed_privatekey

    - name: Signing request
      community.crypto.openssl_csr:
        path: "/tmp/{{ cluster_name }}.csr"
        privatekey_path: "{{ certs_ingress_self_signed_privatekey.filename }}"
        common_name: "{{ cluster_name }}"
        subject_alt_name: "{{ dns_names | map('regex_replace', '^', 'DNS:') | list }}"
      vars:
        dns_names: "{{ [ingress_controller_hostname] + (ingress_controller_addresses | map(attribute='address') | list) }}"
      register: csr

    - name: Self-signed certificate
      community.crypto.x509_certificate:
        path: "/tmp/{{ cluster_name }}.crt"
        privatekey_path: "{{ certs_ingress_self_signed_privatekey.filename }}"
        csr_path: "{{ csr.filename }}"
        ownca_path: "{{ ca_crt.filename }}"
        ownca_privatekey_path: "{{ ownca_privatekey.filename }}"
        provider: ownca
      register: certs_ingress_self_signed_cert
