---
- name: Install dependencies using the Snap package manager
  community.general.snap:
    name: "{{ item }}"
  loop:
    - lxd
  become: true

- name: Initialise LXD
  ansible.builtin.command:
    cmd: lxd init --preseed
    stdin: "{{ lookup('template', 'lxd.yaml.j2') }}"
  become: true
  register: lxd_init
  changed_when: lxd_init.rc != 0

- name: Allow traffic to LXD bridge NIC
  ansible.builtin.shell: |
    ufw allow in on lxcbr0
    ufw route allow in on lxcbr0
    ufw route allow out on lxcbr0
  become: true
  register: ufw
  changed_when: ufw.rc != 0
