---
- name: Install dependencies using the Snap package manager
  community.general.snap:
    name: "{{ item }}"
  loop:
    - lxd
  become: true

- name: Initialise LXD
  ansible.builtin.command:
    cmd: lxd init --preseed
    stdin: "{{ lookup('template', 'lxd.yaml.j2') }}"
  become: true
  register: lxd_init
  changed_when: lxd_init.rc != 0

- name: Allow traffic to LXD bridge NIC
  ansible.builtin.shell: |
    ufw allow in on lxcbr0
    ufw route allow in on lxcbr0
    ufw route allow out on lxcbr0
  become: true
  register: ufw
  changed_when: ufw.rc != 0

- name: Create a VM
  community.general.lxd_container:
    name: mycontainer
    ignore_volatile_options: true
    state: started
    type: virtual-machine
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases/
      protocol: simplestreams
      alias: "22.04"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  become: true

- name: Run a command in the VM
  ansible.builtin.command: >-
    lxc exec mycontainer -- ls -a
  become: true
  register: lxd_exec
  changed_when: lxd_exec.rc != 0
