---
- name: Install limactl
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - lima
    - socket_vmnet

- name: Configure Lima networks
  ansible.builtin.template:
    src: templates/networks.yaml
    dest: ~/.lima/_config/networks.yaml
    mode: "0644"
  register: lima_networks

- name: Regenerate sudoers for Lima
  ansible.builtin.shell:
    cmd: limactl sudoers > /tmp/etc_sudoers.d_lima
  when: lima_networks.changed

- name: Install sudoers for Lima
  ansible.builtin.command:
    cmd: install -o root /tmp/etc_sudoers.d_lima /etc/sudoers.d/lima
  when: lima_networks.changed
  become: true
