---
- name: limactl
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - lima
    - socket_vmnet

- name: VM networks
  ansible.builtin.template:
    src: templates/networks.yaml
    dest: ~/.lima/_config/networks.yaml
    mode: "0644"
  register: hypervisor_vmnet

- name: Rebuild sudoers for Lima
  ansible.builtin.shell:
    cmd: limactl sudoers > /tmp/etc_sudoers.d_lima
  when: hypervisor_vmnet.changed

- name: Install sudoers for Lima
  ansible.builtin.command:
    cmd: install -o root /tmp/etc_sudoers.d_lima /etc/sudoers.d/lima
  when: hypervisor_vmnet.changed
  become: true
