---
- name: Install dependencies using the host's package manager
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - python3-pip
    - pkg-config
    - libvirt-dev
    - libvirt-daemon-system
  become: true

- name: Install libvirt Python bindings
  ansible.builtin.pip:
    name: libvirt-python
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
  become: true
