resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.4/manifests/install.yaml
  - ingress.yaml
  - app-of-apps.yaml

patches:
  - path: patch-configmap.yaml

namespace: argocd
