---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.apps.homenet
  oidc.config: |
    name: GitHub
    issuer: https://auth.apps.homenet
    clientID: $argocd-client:ARGOCD_CLIENT_ID
    clientSecret: $argocd-client:ARGOCD_CLIENT_SECRET
  oidc.tls.insecure.skip.verify: "true" # TODO: harden
# ---
# # Workaround for HAProxy ingress controller
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-cm
# data:
#   resource.customizations: |
#     networking.k8s.io/Ingress:
#       health.lua: |
#         hs = {}
#         hs.status = "Healthy"
#         return hs
