---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  oidc.config: |
    name: Dex
    issuer: https://auth.apps.homenet
    clientID: $argocd-client:ARGOCD_CLIENT_ID
    clientSecret: $argocd-client:ARGOCD_CLIENT_SECRET

# ---
# # Workaround for HAProxy ingress controller
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-cm
# data:
#   resource.customizations: |
#     networking.k8s.io/Ingress:
#       health.lua: |
#         hs = {}
#         hs.status = "Healthy"
#         return hs
