---
- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
  become: true
  listen: keepalived reconfig

- name: Restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
  become: true
  listen: haproxy reconfig
