apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: own-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Latorilla Home Network
  secretName: own-ca
  privateKey:
    algorithm: ECDSA
    size: 256

  duration: 43830h # 5y
  renewBefore: 360h # 15d

  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
