server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    hosts:
      - prometheus.apps.homenet
    tls:
      - hosts:
          - prometheus.apps.homenet
        secretName: prometheus-ingress-tls

  persistentVolume:
    size: 8Gi
    storageClass: openebs-jiva-csi-default
