fullnameOverride: prometheus

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    hosts:
      - prometheus.apps.homenet
    tls:
      - hosts:
          - prometheus.apps.homenet
        secretName: prometheus-ingress-tls
  statefulSet:
    enabled: true

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true
  fullnameOverride: kube-state-metrics

prometheus-node-exporter:
  enabled: true
  fullnameOverride: prometheus-node-exporter

prometheus-pushgateway:
  enabled: true
  fullnameOverride: prometheus-pushgateway
