---
- name: Install kubectl
  community.general.homebrew:
    name: kubernetes-cli

- name: Apply initial manifests
  ansible.builtin.command: kubectl apply -k {{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: cluster_config_kubectl_apply
  changed_when: cluster_config_kubectl_apply.rc != 0
  loop:
    - ../kubernetes/core/00-container-networking
    - ../kubernetes/core/10-ingress-controller
    - ../kubernetes/core/20-argocd

- name: Ingress TLS certificate
  ansible.builtin.shell:
    cmd: |-
      set -o pipefail
      export KUBECONFIG="{{ kubeconfig }}"
      kubectl create secret tls tls \
        -n nginx-ingress \
        --cert {{ ingress_cert }} \
        --key {{ ingress_cert_key }} \
        --dry-run=client \
        -o yaml \
      | kubectl apply -f -
    executable: bash
  register: apply_tls
  changed_when: apply_tls.rc != 0
