---
- name: Prepare destination directory for Registry
  ansible.builtin.file:
    path: /opt/registry
    state: directory
    mode: "0755"
  register: registry_dir
  become: true

- name: Download and install Registry
  ansible.builtin.unarchive:
    src: https://github.com/distribution/distribution/releases/download/v2.8.3/registry_2.8.3_linux_amd64.tar.gz
    remote_src: yes
    dest: "{{ registry_dir.path }}"
  become: true

- name: Create Registry service for systemd
  ansible.builtin.template:
    src: templates/registry.service
    dest: /etc/systemd/system/registry.service
    mode: "0600"
  notify:
    - systemd reload
  become: true

- name: Wait for handlers
  ansible.builtin.meta: flush_handlers

- name: Install TLS certs
  block:
    - name: Registry TLS key
      ansible.builtin.copy:
        src: registry.key
        dest: "{{ registry_dir.path }}/registry.key"
        mode: "0600"
    - name: Registry TLS certificate
      ansible.builtin.copy:
        src: registry.crt
        dest: "{{ registry_dir.path }}/registry.crt"
        mode: "0600"
    - name: Concatenate certs
      ansible.builtin.shell:
        chdir: "{{ registry_dir.path }}"
        cmd: cat registry.crt registry.key > registry.pem
        creates: registry.pem
  become: true

- name: Configure Registry
  ansible.builtin.template:
    src: templates/config.yaml
    dest: "{{ registry_dir.path }}/config.yaml"
    mode: "0600"
  notify:
    - registry reconfig
  become: true

- name: Wait for handlers
  ansible.builtin.meta: flush_handlers
