resources:
  requests:
    cpu: 40m
    memory: 125M
  limits:
    memory: 250M

installation:
  calicoNodeDaemonSet:
    spec:
      template:
        spec:
          containers:
            - name: calico-node
              resources:
                requests:
                  cpu: 50m
                  memory: 400M
                limits:
                  memory: 400M
  csiNodeDaemonSet:
    spec:
      template:
        spec:
          containers:
            - name: calico-csi
              resources:
                requests:
                  cpu: 1m
                  memory: 15M
                limits:
                  memory: 15M
            - name: csi-node-driver-registrar
              resources:
                requests:
                  cpu: 1m
                  memory: 20M
                limits:
                  memory: 20M
  calicoKubeControllersDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-kube-controllers
              resources:
                requests:
                  cpu: 1m
                  memory: 100M
                limits:
                  memory: 100M

  typhaDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-typha
              resources:
                requests:
                  cpu: 10m
                  memory: 60M
                limits:
                  memory: 120M

apiServer:
  apiServerDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-apiserver
              resources:
                requests:
                  cpu: 10m
                  memory: 100M
                limits:
                  memory: 200M
