---
- name: Install QEMU and socket_vmnet
  tags: qemu
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - socket_vmnet
    - qemu

- name: Install services for Homebrew
  tags: qemu
  community.general.homebrew_tap:
    name: homebrew/services

- name: Start socket_vmnet service
  tags: qemu
  ansible.builtin.command:
    cmd: brew services restart socket_vmnet
    creates: /Library/LaunchDaemons/homebrew.mxcl.socket_vmnet.plist
  environment:
    HOMEBREW_NO_INSTALL_FROM_API: "1"
  become: true
