fullnameOverride: cert-manager
installCRDs: true

resources:
  requests:
    cpu: 1m
    memory: 100M
  limits:
    cpu: 5m
    memory: 150M

webhook:
  resources:
    requests:
      cpu: 5m
      memory: 40M
    limits:
      cpu: 10m
      memory: 60M

cainjector:
  resources:
    requests:
      cpu: 5m
      memory: 150M
    limits:
      cpu: 10m
      memory: 225M
