fullnameOverride: cert-manager
installCRDs: true

resources:
  requests:
    cpu: 1m
    memory: 100M
  limits:
    memory: 150M

webhook:
  resources:
    requests:
      cpu: 5m
      memory: 40M
    limits:
      memory: 60M

cainjector:
  resources:
    requests:
      cpu: 5m
      memory: 150M
    limits:
      memory: 225M
