---
- name: Bootstrap the cluster
  tags: kubernetes
  block:
    - name: Install kubectl
      community.general.homebrew:
        name: kubernetes-cli
    - name: Create temporary directory for the ArgoCD manifest
      ansible.builtin.tempfile:
        state: directory
      register: minikube_fetch_argocd_destination_dir
    - name: Download ArgoCD manifest
      ansible.builtin.get_url:
        url: "{{ argocd_manifest_url }}"
        dest: "{{ minikube_fetch_argocd_destination_dir.path }}/install.yaml"
        mode: '0644'
        validate_certs: "{{ ansible_os_family != 'Darwin' }}"
      register: minikube_fetch_argocd_manifest
    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        context: minikube
        resource_definition:
          api_version: v1
          kind: Namespace
          metadata:
            name: argocd
    - name: Install ArgoCD
      kubernetes.core.k8s:
        context: minikube
        namespace: argocd
        src: "{{ minikube_fetch_argocd_manifest.dest }}"
    - name: Bootstrap the cluster
      kubernetes.core.k8s:
        context: minikube
        namespace: argocd
        src: "{{ playbook_dir }}/../kubernetes/argocd/applicationset.yaml"
