---
- name: Bootstrap the cluster
  tags: kubernetes
  block:
    - name: Install kubectl
      community.general.homebrew:
        name: kubernetes-cli
    - name: Bootstrap the cluster
      ansible.builtin.command: kubectl apply -k ../kubernetes/argocd
      register: minikube_apply_kustomize
      changed_when: true
