---
- name: Install kubectl
  tags: kubernetes
  community.general.homebrew:
    name: kubernetes-cli

- name: Bootstrap the cluster
  tags: kubernetes
  ansible.builtin.command: "kubectl apply -k {{ item }}"
  changed_when: true
  loop:
    - ../kubernetes/haproxy-controller
    - ../kubernetes/argocd
    - ../kubernetes/app-of-apps
