apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
    - git:
        repoURL: https://github.com/ginolatorilla/k8s-homenet.git
        revision: HEAD
        directories:
          - path: kubernetes/*
          - path: kubernetes/argocd
            exclude: true
          - path: kubernetes/app-of-apps
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/ginolatorilla/k8s-homenet.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
