---
- name: Install DNSMasq as external DNS
  tags: dnsmasq
  ansible.builtin.package:
    name: dnsmasq

- name: Configure DNSMasq
  tags: dnsmasq
  ansible.builtin.template:
    src: templates/dnsmasq.conf
    dest: "{{ ansible_env.HOMEBREW_PREFIX }}/etc/dnsmasq.conf"
    mode: '0644'

- name: Install services for Homebrew
  tags: dnsmasq
  community.general.homebrew_tap:
    name: homebrew/services

- name: Start DNSMasq as a service
  tags: dnsmasq
  ansible.builtin.command:
    cmd: brew services restart dnsmasq
  register: dnsmasq_service_restart
  changed_when: true
  environment:
    HOMEBREW_NO_INSTALL_FROM_API: "1"
  become: true

- name: Register a new DNS server to the host
  tags: dnsmasq
  ansible.builtin.template:
    src: templates/resolver
    dest: "/etc/resolver/{{ domain }}"
    mode: '0644'
