nameOverride: vault

injector:
  resources:
    requests:
      cpu: 20m
      memory: 50M
    limits:
      cpu: 25m
      memory: 75M

server:
  resources:
    requests:
      cpu: 100m
      memory: 400M
    limits:
      cpu: 150m
      memory: 600M
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ingress-cert-issuer
    ingressClassName: nginx
    hosts:
      - vault.apps.homenet
    tls:
      - secretName: vault-tls
        hosts:
          - vault.apps.homenet

  dataStorage:
    storageClass: openebs-jiva-csi-default

  standalone:
    enabled: true
