fullnameOverride: vault

injector:
  resources:
    requests:
      cpu: 20m
      memory: 50M
    limits:
      memory: 75M

server:
  resources:
    requests:
      cpu: 100m
      memory: 400M
    limits:
      memory: 600M
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ingress-cert-issuer
    ingressClassName: nginx
    hosts:
      - host: vault.apps.homenet
        path: []
    tls:
      - secretName: vault-tls
        hosts:
          - vault.apps.homenet

  dataStorage:
    enabled: false

  standalone:
    enabled: true
