# -*- mode: ruby -*-
# vi: set ft=ruby :

# Kubernetes for Home Network provisioner
# Inspired by Artur Scheiner - artur.scheiner@gmail.com

CLUSTER_NAME = "k8s-homenet"
HOST_NAME = "host-0-darwin-aarch64"
POD_CIDR = "172.18.0.0/16"

Vagrant.configure("2") do |config|
  config.vm.box = "starboard/ubuntu-arm64-20.04.5"
  config.vm.box_version = "20221120.20.40.0"
  config.vm.provider :vmware_desktop do |v, override|
    v.ssh_info_public = true
    v.gui = true
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    v.vmx["ethernet0.connectiontype"] = "bridged"
  end

  config.vm.define "#{HOST_NAME}-k8s-master-0" do |node|
    node.vm.hostname = "#{HOST_NAME}-k8s-master-0"
    node.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "2048"
    end
    node.vm.provision "shell", path: "../scripts/install-master.sh", args: ["k8s-homenet", POD_CIDR]
  end

  config.vm.define "#{HOST_NAME}-k8s-infra-0" do |node|
    node.vm.hostname = "#{HOST_NAME}-k8s-infra-0"
    node.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "1024"
      v.vmx["ethernet0.addressType"] = "static"
      v.vmx["ethernet0.address"] = "00:0C:29:09:7D:78"
    end
    node.vm.provision "shell", path: "../scripts/install-infra.sh"
  end

  config.vm.define "host0-darwin-aarch64-dns" do |node|
    node.vm.hostname = "host0-darwin-aarch64-dns"
    node.vm.provider :vmware_desktop do |v|
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "512"
      v.vmx["ethernet0.addressType"] = "static"
      v.vmx["ethernet0.address"] = "00:0C:29:69:2A:FB"
    end

    node.vm.provision "install-app", type: "shell", path: "./scripts/install-dns.sh"
    node.vm.provision "put-config", after: "install-app", type: "file", source: "./etc/dnsmasq.conf", destination: "/tmp/etc/dnsmasq.conf"
    node.vm.provision "reload-config", after: "put-config", type: "shell", path: "./scripts/reload-dns.sh"
  end

end
