# -*- mode: ruby -*-
# vi: set ft=ruby :

# Kubernetes for Home Network provisioner
# Inspired by by Artur Scheiner - artur.scheiner@gmail.com

BOX_IMAGE = "starboard/ubuntu-arm64-20.04.5"
BOX_VERSION = "20221120.20.40.0"
CLUSTER_NAME = "k8s-homenet"
MASTER_COUNT = 1
WORKER_COUNT = 0
INFRA_COUNT = 1
POD_CIDR = "172.18.0.0/16"
API_ADV_ADDRESS = "10.8.8.10"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_version = BOX_VERSION
  config.vm.provider :vmware_desktop do |v, override|
    v.ssh_info_public = true
    v.gui = true
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    v.vmx["ethernet0.connectiontype"] = "bridged"
  end

  (0..MASTER_COUNT-1).each do |i|
    config.vm.define "#{CLUSTER_NAME}-master-#{i}" do |node|
      node.vm.box = BOX_IMAGE
      node.vm.box_version = BOX_VERSION
      node.vm.hostname = "#{CLUSTER_NAME}-master-#{i}"
      node.vm.provider :vmware_desktop do |v, override|
        v.ssh_info_public = true
        v.gui = true
        v.vmx["numvcpus"] = "2"
        v.vmx["memsize"] = "2048"
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      end
      node.vm.provision "shell", path: "../scripts/install-master.sh", args: [CLUSTER_NAME, POD_CIDR]
    end
  end
  
  (0..INFRA_COUNT-1).each do |i|
    config.vm.define "#{CLUSTER_NAME}-infra-#{i}" do |node|
      node.vm.box = BOX_IMAGE
      node.vm.box_version = BOX_VERSION
      node.vm.hostname = "#{CLUSTER_NAME}-infra-#{i}"
      node.vm.provider :vmware_desktop do |v, override|
        v.ssh_info_public = true
        v.gui = true
        v.vmx["numvcpus"] = "1"
        v.vmx["memsize"] = "1024"
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.vmx["ethernet0.connectiontype"] = "bridged"
        v.vmx["ethernet0.addressType"] = "static"
        v.vmx["ethernet0.address"] = "00:0C:29:09:7D:78"
      end
      node.vm.provision "shell", path: "../scripts/install-infra.sh"
    end
  end

  config.vm.define "host0-darwin-aarch64-dns" do |node|
    node.vm.hostname = "host0-darwin-aarch64-dns"
    node.vm.provider :vmware_desktop do |v|
      v.ssh_info_public = true
      v.gui = true
      v.vmx["numvcpus"] = "1"
      v.vmx["memsize"] = "512"
      v.vmx["ethernet0.addressType"] = "static"
      v.vmx["ethernet0.address"] = "00:0C:29:69:2A:FB"
    end
    node.vm.provision "shell", path: "../scripts/install-infra.sh"
  end

end
