fullnameOverride: argocd

global:
  domain: argocd.apps.homenet

controller:
  resources:
    requests:
      cpu: 500m
      memory: 1G
    limits:
      memory: 1.5G

dex:
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      memory: 150M

redis:
  resources:
    requests:
      cpu: 3m
      memory: 16M
    limits:
      memory: 24M

server:
  resources:
    requests:
      cpu: 50m
      memory: 120M
    limits:
      memory: 180M
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    tls: true

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 500M
    limits:
      memory: 1G

applicationSet:
  resources:
    requests:
      cpu: 150m
      memory: 150M
    limits:
      memory: 225M

notifications:
  resources:
    requests:
      cpu: 20m
      memory: 80M
    limits:
      memory: 120M

configs:
  cm:
    create: true
    # The secret argocd-client must have this label: `app.kubernetes.io/part-of: argocd`
    oidc.config: |
      name: GitHub via Dex
      issuer: https://auth.apps.homenet
      clientID: $argocd-client:ARGOCD_CLIENT_ID
      clientSecret: $argocd-client:ARGOCD_CLIENT_SECRET
    oidc.tls.insecure.skip.verify: "true"
    resource.customizations: |
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle

  params:
    server.insecure: true

  rbac:
    policy.csv: |
      g, pblatorilla+github@gmail.com, role:admin

    policy.default: role:readonly
    scopes: "[groups, email, preferred_username]"
