apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  selector:
    app.kubernetes.io/name: nginx-ingress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 30443
  type: NodePort
