---
- name: SSL certificates
  tags: s0
  hosts: baremetal
  roles:
    - role: certs

- name: Virtual machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
    - role: virtual_machine
      vars:
        virtual_machine_vms: "{{ groups.all | difference(groups.baremetal) | map('replace', 'lima-', '') }}"

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
  become: true

- name: Kubernetes infra nodes
  tags: s3
  hosts: k8sinfra
  roles:
    - role: cluster_bootstrap
      vars:
        kubeconfig: /tmp/kubeconfig
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
        control_plane_endpoint: "{{ control_plane_addresses[0].address }}:{{ control_plane_port }}"
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        kubeconfig: /tmp/kubeconfig
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
        control_plane_endpoint: "{{ control_plane_addresses[0].address }}:{{ control_plane_port }}"
  become: true

- name: Kubernetes config
  tags: s5
  hosts: localhost
  roles:
    - role: cluster_config
      vars:
        kubeconfig: /tmp/kubeconfig
        ingress_cert: "{{ certs_ingress_self_signed_cert.filename }}"
        ingress_cert_key: "{{ certs_ingress_self_signed_privatekey.filename }}"
