---
- name: Launch Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
    - role: nodes
      vars:
        node_name: k8s-homenet-control-0
        mac_address: "52:7b:31:6a:fc:34"
    - role: nodes
      vars:
        node_name: k8s-homenet-worker-0
        mac_address: "52:7b:31:6a:fc:35"

- name: Setup Kubernetes Control Plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: control-plane
  become: true

- name: Setup Kubernetes Workers
  tags: s3
  hosts: k8sworkers
