---
- name: Launch Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
    - role: control-plane-nodes
      vars:
        control_node_name: k8s-homenet-control-0
        mac_address: "52:7b:31:6a:fc:34"

- name: Setup Kubernetes Control Plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: control-plane
  become: true
