---
- name: Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
      vars:
        node_network_gateway: "10.0.0.0"
        node_network_mask: "255.0.0.0"
    - role: nodes
      vars:
        node_name: k8s-homenet-control-0
        mac_address: "52:7b:31:6a:fc:34"
    - role: nodes
      vars:
        node_name: k8s-homenet-worker-0
        mac_address: "52:7b:31:6a:fc:35"
    - role: nodes
      vars:
        node_name: k8s-homenet-worker-1
        mac_address: "52:7b:31:6a:fc:36"

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        control_plane_address: "192.168.100.250"
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        control_plane_address: "192.168.100.250"
        control_plane_endpoint: "192.168.100.250:6443"
  become: true
