---
- name: Launch the Kubernetes cluster
  hosts: localhost
  roles:
    - role: minikube
      vars:
        rebuild_cluster: true
    - role: dnsmasq
      vars:
        listen_address: "{{ minikube_get_default_route.stdout }}"
        domain: homenet
        kubernetes_ingress_ip: "{{ minikube_ip.stdout }}"
    - role: kubernetes
      vars:
        manifests:
          - url: https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
            namespace: argocd
          - url: https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml
            namespace: haproxy-controller
