---
- name: Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
  tasks:
    - name: Provision VMs
      ansible.builtin.include_role:
        name: virtual_machine
      vars:
        virtual_machine_name: "{{ item }}"
      loop: "{{ groups.all | difference(groups.baremetal) | map('replace', 'lima-', '') }}"

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        kubernetes_node_ip: "{{ ansible_bridge.ipv4.address }}"
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        kubernetes_node_ip: "{{ ansible_bridge.ipv4.address }}"
        control_plane_endpoint: "{{ control_plane_address }}:{{ control_plane_port }}"
  become: true
