---
- name: Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
      vars:
        node_network_gateway: "10.0.0.0"
        node_network_mask: "255.0.0.0"
  tasks:
    - name: Provision VMs
      ansible.builtin.include_role:
        name: virtual_machine
      vars:
        virtual_machine_name: "{{ item }}"
      loop:
        - k8s-homenet-control-0
        - k8s-homenet-worker-0
        - k8s-homenet-worker-1

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        cluster_name: k8s-homenet
        control_plane_address: "192.168.100.250"
        haproxy_control_plane_hosts:
          k8s-control-node-0: "{{ hostvars['lima-k8s-homenet-control-0'].ansible_bridge.ipv4.address }}"
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        cluster_name: k8s-homenet
        control_plane_address: "192.168.100.250"
        control_plane_endpoint: "192.168.100.250:6443"
  become: true
