---
- name: Preparations
  tags: s0
  hosts: localhost
  tasks:
    - name: Install requirements
      ansible.builtin.package:
        name:
          - kubernetes-cli
          - helm
      # Homebrew doesn't need root; uncomment if necessary in other OSes.
      # become: true
  roles:
    - certificates

- name: Compute
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
    - role: loadbalancer
    - role: virtual_machine

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        control_plane_endpoint: "{{ control_plane_hostname }}:{{ control_plane_port }}"
  become: true

- name: Kubernetes config
  tags: s4
  hosts: localhost
  roles:
    - role: cluster_config
      environment:
        KUBECONFIG: "{{ kubeconfig | expanduser }}"
