---
- name: Virtual Machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
      vars:
        node_network_gateway: "10.0.0.0"
        node_network_mask: "255.0.0.0"
  tasks:
    - name: Provision control node 0
      ansible.builtin.include_role:
        name: nodes
      vars:
        node_name: k8s-homenet-control-0
        mac_address: "d5:a0:d8:ca:18:ed"
    - name: Provision worker node 0
      ansible.builtin.include_role:
        name: nodes
      vars:
        node_name: k8s-homenet-worker-0
        mac_address: "ea:7f:cf:ab:52:d1"
    - name: Provision worker node 1
      ansible.builtin.include_role:
        name: nodes
      vars:
        node_name: k8s-homenet-worker-1
        mac_address: "a2:51:ef:4a:9a:a4"

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        cluster_name: k8s-homenet
        control_plane_address: "192.168.100.250"
        haproxy_control_plane_hosts:
          k8s-control-node-0: "192.168.100.128"
  become: true

- name: Kubernetes workers
  tags: s3
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        cluster_name: k8s-homenet
        control_plane_address: "192.168.100.250"
        control_plane_endpoint: "192.168.100.250:6443"
  become: true
