---
- name: Virtual machines
  tags: s1
  hosts: baremetal
  roles:
    - role: hypervisor
    - role: virtual_machine
      vars:
        virtual_machine_vms: "{{ groups.all | difference(groups.baremetal) | map('replace', 'lima-', '') }}"

- name: Kubernetes control plane
  tags: s2
  hosts: k8scontrollers
  roles:
    - role: cluster_bootstrap
      vars:
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
        static_host_ips:
          control_plane: "{{ control_plane_addresses[1].address }}"
          ingress_controller: "{{ ingress_controller_addresses[1].address }}"
  become: true

- name: Kubernetes CNI
  tags: s2
  hosts: localhost
  tasks:
    - name: Install CNI from manifests
      ansible.builtin.command: kubectl apply -k ../kubernetes/core/00-container-networking
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: cni_install
      changed_when: cni_install.rc != 0
    - name: Wait for CNI
      ansible.builtin.command: kubectl wait -n kube-system deploy/calico-kube-controllers --for condition=available
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: cni_wait
      changed_when: cni_wait.rc != 0

- name: Kubernetes infra nodes
  tags: s3
  hosts: k8sinfra
  roles:
    - role: cluster_bootstrap
      vars:
        kubeconfig: /tmp/kubeconfig
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
        control_plane_endpoint: "{{ control_plane_hostname }}:{{ control_plane_port }}"
        static_host_ips:
          control_plane: "{{ control_plane_addresses[1].address }}"
          ingress_controller: "{{ ingress_controller_addresses[1].address }}"
  become: true

- name: Kubernetes workers
  tags: s4
  hosts: k8sworkers
  roles:
    - role: cluster_bootstrap
      vars:
        kubeconfig: /tmp/kubeconfig
        kubernetes_node_ip: "{{ ansible_vm.ipv4.address }}"
        control_plane_endpoint: "{{ control_plane_hostname }}:{{ control_plane_port }}"
        static_host_ips:
          control_plane: "{{ control_plane_addresses[1].address }}"
          ingress_controller: "{{ ingress_controller_addresses[1].address }}"
  become: true

- name: Kubernetes config
  tags: s5
  hosts: localhost
  roles:
    - role: cluster_config
      vars:
        kubeconfig: /tmp/kubeconfig
