---
- name: Launch the Kubernetes cluster
  hosts: localhost
  roles:
    - role: limactl
    - role: control-plane
      vars:
        control_node_name: k8s-homenet-control-0
        mac_address: "52:7b:31:6a:fc:34"
