---
- name: Preparations
  hosts: localhost
  tasks:
    - name: Install requirements
      tags: requirements
      ansible.builtin.package:
        name:
          - kubernetes-cli
          - helm
      become: "{{ ansible_os_family != 'Darwin' }}"
  roles:
    - role: certificates
      tags: certs

- name: Compute
  hosts: vm_hosts
  tags: compute
  roles:
    - role: hypervisor
    - role: virtual_machine

- name: Kubernetes control node (leader)
  tags: control_plane
  hosts: k8s_control_node_leader
  roles:
    - role: cluster_bootstrap
  become: true

- name: Kubernetes control node (followers)
  tags: control_plane
  hosts: k8s_control_nodes
  roles:
    - role: cluster_bootstrap
  become: true

- name: Kubernetes workers
  tags: workers
  hosts: k8s_workers
  roles:
    - role: cluster_bootstrap
  become: true

- name: Cluster config
  tags: cluster_config
  hosts: localhost
  roles:
    - role: cluster_config
      environment:
        KUBECONFIG: "{{ kubeconfig | expanduser }}"
