baremetal:
  hosts:
    localhost:
      ansible_connection: local

k8scontrollers:
  hosts:
    lima-k8s-homenet-control-0:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-control-0/ssh.config"
      kubernetes_node_type: "control-leader"

k8sworkers:
  hosts:
    lima-k8s-homenet-worker-0:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-0/ssh.config"
      kubernetes_node_type: "worker"
    lima-k8s-homenet-worker-1:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-1/ssh.config"
      kubernetes_node_type: "worker"
