all:
  vars:
    cluster_name: k8s-homenet
    control_plane_hostname: api.k8s.homenet
    control_plane_address: "192.168.100.250" # Virtual IP must be addressable in the home router's subnet
    control_plane_port: "6443"
    ingress_controller_hostname: homenet
    ingress_controller_address: "192.168.100.251" # Virtual IP must be addressable in the home router's subnet
    ingress_controller_port: "443"
    kubernetes_node_cidr: "10.0.0.1/16"
    kubernetes_service_cidr: "172.16.0.0/18"
    kubernetes_pod_cidr: "10.85.0.0/16" # CRIO's default (hardcoded); TODO: implement
    kubeconfig: ~/.kube/config.k8s-homenet

    # Default values for virtual machines
    vm_cpu: 2
    vm_memory: 2GiB
    vm_disk: 8GiB

baremetal:
  hosts:
    homenet-baremetal-0:
      ansible_ssh_host: homenet-baremetal-0.local
      ansible_become_pass: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65396332313230613033383663643034636638336533336135366662656561323135663666663635
        6464643735313338663933636561616166636636316632310a363333343463366138376637313861
        32323136303139663832333035666361373462646233376135613230623166653530613139363063
        3033313766306636360a623930343638623265376331323662303361633938373734653531343961
        6636
      hypervisor: lxd
      loadbalancer:
        role: MASTER
        priority: "101"
      datastore:
        size: 64GiB
      virtual_machines:
        homenet-k8s-control-0:
          memory: 4GiB
          ipv4_address: "10.0.0.2"
        homenet-k8s-worker-small-b35aeecb-4c47:
          disk: 18GiB
          ipv4_address: "10.0.0.3"
        homenet-k8s-worker-small-b35aeecb-9833:
          disk: 18GiB
          ipv4_address: "10.0.0.4"
        homenet-k8s-worker-small-b35aeecb-61ed:
          disk: 18GiB
          ipv4_address: "10.0.0.5"

k8scontrollers:
  hosts:
    homenet-k8s-control-0:
      ansible_host: "10.0.0.2"
      ansible_host_key_checking: false
      ansible_ssh_extra_args: >-
        -o User=root
        -o ForwardAgent=yes
        -o ProxyJump=homenet-baremetal-0.local
      kubernetes_node_type: control
      kubernetes_node_role: leader

k8sworkers:
  hosts:
    homenet-k8s-worker-small-b35aeecb-4c47:
      ansible_host: "10.0.0.3"
      ansible_host_key_checking: false
      ansible_ssh_extra_args: >-
        -o User=root
        -o ForwardAgent=yes
        -o ProxyJump=homenet-baremetal-0.local
      kubernetes_node_type: worker
    homenet-k8s-worker-small-b35aeecb-9833:
      ansible_host: "10.0.0.4"
      ansible_host_key_checking: false
      ansible_ssh_extra_args: >-
        -o User=root
        -o ForwardAgent=yes
        -o ProxyJump=homenet-baremetal-0.local
      kubernetes_node_type: worker
    homenet-k8s-worker-small-b35aeecb-61ed:
      ansible_host: "10.0.0.5"
      ansible_host_key_checking: false
      ansible_ssh_extra_args: >-
        -o User=root
        -o ForwardAgent=yes
        -o ProxyJump=homenet-baremetal-0.local
      kubernetes_node_type: worker
