all:
  vars:
    cluster_name: k8s-homenet
    control_plane_address: "192.168.100.250"
    control_plane_port: "6443"
    node_network_gateway: "10.0.0.0"
    node_network_mask: "255.0.0.0"

baremetal:
  hosts:
    localhost:
      ansible_connection: local
    # secondary:
    #   ansible_connection: "192.168.100.7"

k8scontrollers:
  hosts:
    # 128 to 135 - control plane
    lima-k8s-homenet-control-0:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-control-0/ssh.config"
      kubernetes_node_type: "control-leader"
      vm_host: localhost
    # lima-k8s-homenet-control-1:
    #   ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-control-1/ssh.config"
    #   kubernetes_node_type: "control"
    #   vm_host: localhost
    # lima-k8s-homenet-control-2:
    #   ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-control-2/ssh.config"
    #   kubernetes_node_type: "control"
    #   vm_host: localhost
    # 136 to 143 - infra nodes

    # lima-k8s-homenet-infra-1:
    #   ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-0/ssh.config"
    #   kubernetes_node_type: "worker"
    #   vm_host: localhost

k8sworkers:
  hosts:
    # 144 to 159 - workers
    lima-k8s-homenet-worker-0:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-0/ssh.config"
      kubernetes_node_type: "worker"
      vm_host: localhost

    lima-k8s-homenet-worker-1:
      ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-1/ssh.config"
      kubernetes_node_type: "worker"
      vm_host: localhost
