all:
  vars:
    cluster_name: k8s-homenet
    control_plane_hostname: api.k8s.homenet
    control_plane_addresses:
      - interface: bridge
        address: "192.168.100.250"
      - interface: vm
        address: "192.168.10.25"
    control_plane_port: "6443"
    ingress_controller_hostname: homenet
    ingress_controller_addresses:
      - interface: bridge
        address: "192.168.100.251"
      - interface: vm
        address: "192.168.10.26"
    ingress_controller_port: "443"
    kubernetes_node_cidr: "10.0.0.1/16"
    kubernetes_service_cidr: "172.16.0.0/18"
    kubernetes_pod_cidr: "10.85.0.0/16" # CRIO's default (hardcoded)
    kubernetes_version: "1.29.0"

    # Default values for virtual machines
    vm_cpu: 2
    vm_memory: 2GiB
    vm_disk: 8GiB

baremetal:
  hosts:
    homenet-baremetal-0:
      ansible_ssh_host: homenet-baremetal-0.local
      ansible_become_pass: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65396332313230613033383663643034636638336533336135366662656561323135663666663635
        6464643735313338663933636561616166636636316632310a363333343463366138376637313861
        32323136303139663832333035666361373462646233376135613230623166653530613139363063
        3033313766306636360a623930343638623265376331323662303361633938373734653531343961
        6636
      hypervisor: lxd
      virtual_machines:
        homenet-k8s-control-0:
          cpu: 2
          memory: 2560MiB
          ipv4_address: "10.0.0.2"
  # localhost:
  #   ansible_connection: local
  #   node_network_gateway: "192.168.10.1"
  #   node_network_dhcp_end: "192.168.10.30"
  #   node_network_mask: "255.255.255.224"

k8scontrollers:
  hosts:
    homenet-k8s-control-0:
      # ansible_ssh_host: "10.203.193.111"
      # ansible_host_key_checking: false
      # ansible_ssh_extra_args: >-
      #   -o User=root
      #   -o ForwardAgent=yes
      #   -o ProxyJump=homenet-baremetal-0.local
    # lima-k8s-homenet-control-0:
    #   ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-control-0/ssh.config"
    #   kubernetes_node_type: "control"
    #   vm_host: localhost
    #   vm_memory: 2.5GiB
    #   cluster_bootstrap_keepalived_state: MASTER
    #   cluster_bootstrap_keepalived_priority: "101"
# k8sinfra:
#   hosts:
#     lima-k8s-homenet-infra-0:
#       ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-infra-0/ssh.config"
#       kubernetes_node_type: "infra"
#       vm_host: localhost
#       vm_memory: 2.5GiB
#       cluster_bootstrap_keepalived_state: MASTER
#       cluster_bootstrap_keepalived_priority: "101"

# k8sworkers:
#   hosts:
#     lima-k8s-homenet-worker-0:
#       ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-0/ssh.config"
#       kubernetes_node_type: "worker"
#       vm_host: localhost
#       vm_memory: 4GiB
#       vm_disk: 16GiB

#     lima-k8s-homenet-worker-1:
#       ansible_ssh_extra_args: "-F /Users/gino.latorilla/.lima/k8s-homenet-worker-1/ssh.config"
#       kubernetes_node_type: "worker"
#       vm_host: localhost
#       vm_memory: 4GiB
#       vm_disk: 16GiB
