---
- name: Install Minikube
  ansible.builtin.package:
    name: minikube

- name: Install QEMU as a Minikube driver
  block:
    - name: Install Minikube drivers
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - socket_vmnet
        - qemu
    - name: Install services for Homebrew
      community.general.homebrew_tap:
        name: homebrew/services
    - name: Start service
      ansible.builtin.command:
        cmd: brew services restart socket_vmnet
        creates: /Library/LaunchDaemons/homebrew.mxcl.socket_vmnet.plist
      environment:
        HOMEBREW_NO_INSTALL_FROM_API: "1"
      become: true
