---
- name: Install Minikube
  tags: minikube_deps
  block:
    - name: Install Minikube and drivers
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - minikube
        - socket_vmnet
        - qemu
    - name: Install services for Homebrew
      community.general.homebrew_tap:
        name: homebrew/services
    - name: Start service
      ansible.builtin.command:
        cmd: brew services restart socket_vmnet
        creates: /Library/LaunchDaemons/homebrew.mxcl.socket_vmnet.plist
      environment:
        HOMEBREW_NO_INSTALL_FROM_API: "1"
      become: true

- name: Launch Minikube
  ansible.builtin.command: minikube start --driver qemu --network socket_vmnet
  register: minikube_start
  changed_when: minikube_start.rc != 0
  tags: minikube
