---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/dashboard/'
    targetRevision: 6.0.0
    chart: kubernetes-dashboard
    helm:
      values: |
        service:
          externalPort: 80
        protocolHttp: true
        extraArgs:
          - --enable-skip-login
          - --enable-insecure-login
          - --system-banner="Welcome to Kubernetes"
        ingress:
          enabled: true
          className: haproxy
          hosts: ["kubernetes-dashboard.apps.homenet"]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
