config:
  issuer: https://auth.apps.homenet
  storage:
    type: sqlite3 # TODO: Upgrade to a DB service later
    config:
      file: /tmp/dex.db
  enablePasswordDB: true
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://auth.apps.homenet/callback
  staticClients:
    - name: ArgoCD
      id: argocd
      secret: "1234" # TODO: harden
      redirectURIs:
        - https://argocd.apps.homenet/auth/callback

envFrom:
  - secretRef:
      name: github-oauth

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "ingress-cert-issuer"
  hosts:
    - host: auth.apps.homenet
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - auth.apps.homenet
      secretName: dex-ingress-tls
