controller:
  resources:
    requests:
      cpu: 40m
      memory: 100M
    limits:
      memory: 150M
  service:
    type: NodePort
    httpPort:
      nodePort: 30080
    httpsPort:
      nodePort: 30443

  extraArgs:
    report-ingress-status:
