---
- name: Kubernetes binaries
  block:
    - name: Kubernetes apt repo signing keys
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Kubernetes apt repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present

    - name: Kubernetes packages
      ansible.builtin.apt:
        update_cache: true
        package:
          - kubelet
          - kubeadm
          - kubectl

- name: Kubelet as a systemd service
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true
    masked: false
    state: started

- name: Cluster bootstrapping
  ansible.builtin.command:
    cmd: kubeadm init --pod-network-cidr "10.85.0.0/16" --cri-socket=unix:///var/run/crio/crio.sock
    creates: /etc/kubernetes/manifests/*.yaml
