---
- name: Add Kubernetes APT repository
  block:
    - name: Install apt repo deps
      ansible.builtin.apt:
        update_cache: true
        package:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Get signing key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present

- name: Install kubeadm
  ansible.builtin.apt:
    update_cache: true
    package:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable the kubelet
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true
    masked: false
    state: started
