fullnameOverride: openebs

localprovisioner:
  deviceClass:
    enabled: false

  basePath: /var/openebs/local

jiva:
  enabled: true

  storageClass:
    name: openebs-jiva-csi-default

  defaultPolicy:
    name: openebs-jiva-default-policy
    replicas: 1
