fullnameOverride: openebs

localprovisioner:
  deviceClass:
    enabled: false
  basePath: /var/openebs/local
  resources:
    requests:
      cpu: 15m
      memory: 50M
    limits:
      memory: 75M

ndm:
  enabled: false

ndmOperator:
  enabled: false
